### ISSUE TITLE
sdk s3 operations fail when AWS4SignerType is used to create request

### ISSUE THREAD

**Issue by arempter** [arempter/gargoyle-s3proxy#9]
**sdk v4 requests fail with:**
Not allowed null (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: tx000000000000000000110-005b4df55d-34452-default; S3 Extended Request ID: 34452-default-default)

Without proxy the same code works. 

**Ceph output shows:**
2018-07-17 13:55:41.031092 7f9881963700 15 server signature=7297fead33ecc6d34001fca3bad45648c17d713751776955bec7ffc9021a1eca
2018-07-17 13:55:41.031095 7f9881963700 15 client signature=a4a85ca5276107b323948496ba05f91472c5a62377685e91e19223bf51be3e70
2018-07-17 13:55:41.031096 7f9881963700 15 compare=42
2018-07-17 13:55:41.031100 7f9881963700 20 rgw::auth::s3::LocalEngine denied with reason=-2027
2018-07-17 13:55:41.031101 7f9881963700 20 rgw::auth::s3::AWSAuthStrategy denied with reason=-2027

**Comment by bolkedebruin** [comment]
The cli seems not to sign the host correctly (“host” vs “Host” in the sdk)

**Comment by bolkedebruin** [comment]
https://github.com/aws/aws-cli/issues/3456

**Comment by arempter** [comment]
I just did test with my own signed request (v4) using AWS4Signer class, and I get ok response.
The only difference so far I see is that my own request is similar to cli one, that is:

canonical headers format = host:192.168.56.1:8080
SignedHeaders=host;x-amz-date, 

I will investigate more, tomorrow.

**Comment by bolkedebruin** [comment]
“host” is not a header, ie. It is undefined. Try to see if you can make it uppercase “H”

**Comment by arempter** [comment]
Request I generate has correct header:

GET http://192.168.56.1:8080 /test1 Headers: (Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXX/20180717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=XXXXXX, x-amz-content-sha256: XXXXXX, X-Amz-Date: 20180717T180910Z, User-Agent: aws-sdk-java/1.11.358 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13 java/1.8.0_121 scala/2.12.6, **Host: 192.168.56.1:8080**, amz-sdk-invocation-id: ba476bb5-f398-17b0-eb29-7b6837a5fdce, amz-sdk-retry: 0/0/500, )

The code in AWS4Signer is:
protected void addHostHeader(SignableRequest<?> request) {
 // AWS4 requires that we sign the Host header so we
// have to have it in the request by the time we sign.
...
}

and the output with:
2018-07-17 18:09:08.953755 7fea053ab700 10 canonical headers format = host:192.168.56.1:8080

comes from radosGW

**Comment by bolkedebruin** [comment]
No it doesn’t. It refers to “host” (Lowercase) in the signed headers. That header does not exist.it is case sensitive

**Comment by bolkedebruin** [comment]
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L229

So we would need set the endpoint (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L537) of the request to ceph's endpoint.

**Comment by bolkedebruin** [comment]
But something seems off...

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L523

(which translates it to lowercase)

**Comment by arempter** [comment]
ceph doesn't report via proxy. Without it does:
2018-07-18 10:53:48.618306 7f42884ef700 20 CONTENT_LENGTH=0

**Comment by arempter** [comment]
https://github.com/akka/akka-http/issues/1550

https://github.com/jrudolph/akka-http/commit/7eaa150061e5765309b2d17fd03cbaa42a548057

 private val alwaysParsedHeaders = Set[String](
+    "connection",
+    "content-length",
+    "content-type",
+    "expect",
+    "host",
+    "transfer-encoding"
+  )
